# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1dd843b46d2d2213cd00444d79cb657f590381efc1483371f04283bafc4b0077537f4bc2a7c2bfdd9b6a864acbcf70778ec0190094a067fa3ba6361481d8ce5

test:
  secret_key_base: 0b9617b2190b86368aa3cad6f8db37467ac68c7892be9c8f99b24fd0d1e45cc83a59ad03c9bcd5aef8467d2312a3c6a42b162d4b6e53d47b6d7e8d420abab4bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
